<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Fixer\Comment;

use PhpCsFixer\AbstractFixer;
use PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\ConfigurableFixerTrait;
use PhpCsFixer\Fixer\WhitespacesAwareFixerInterface;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
use PhpCsFixer\Preg;
use PhpCsFixer\PregException;
use PhpCsFixer\Tokenizer\Tokens;
use Symfony\Component\OptionsResolver\Options;

/**
 * @phpstan-type _AutogeneratedInputConfiguration array{
 *  comment_type?: 'PHPDoc'|'comment',
 *  header: string,
 *  location?: 'after_declare_strict'|'after_open',
 *  separate?: 'both'|'bottom'|'none'|'top',
 *  validator?: null|string,
 *  files_pattern?: null|string,
 *  files_regex_exclude?: null|string,
 * }
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 *  comment_type: 'PHPDoc'|'comment',
 *  header: string,
 *  location: 'after_declare_strict'|'after_open',
 *  separate: 'both'|'bottom'|'none'|'top',
 *  validator: null|string,
 *  files_pattern: null|string,
 *  files_regex_exclude: null|string,
 * }
 *
 * @implements ConfigurableFixerInterface<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration>
 *
 * @author Antonio J. García Lagar <aj@garcialagar.es>
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class HeaderCommentWithFilterFixer extends AbstractFixer implements ConfigurableFixerInterface, WhitespacesAwareFixerInterface
{
    /** @use ConfigurableFixerTrait<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration> */
    use ConfigurableFixerTrait;

    private HeaderCommentFixer $headerCommentFixer;

    public function __construct()
    {
        $this->headerCommentFixer = new HeaderCommentFixer();
    }

    public function getDefinition(): FixerDefinitionInterface
    {
        return new FixerDefinition(
            'Add, replace or remove header comment with file filtering.',
            [
                new CodeSample(
                    <<<'PHP'
                        <?php
                        declare(strict_types=1);

                        namespace A\B;

                        echo 1;

                        PHP,
                    [
                        'header' => 'Made with love.',
                        'files_pattern' => '/\.php$/',
                    ],
                ),
                new CodeSample(
                    <<<'PHP'
                        <?php
                        declare(strict_types=1);

                        namespace A\B;

                        echo 1;

                        PHP,
                    [
                        'header' => 'Made with love.',
                        'files_pattern' => '/\.php$/',
                        'files_regex_exclude' => '/^tests\//',
                        'comment_type' => 'PHPDoc',
                        'location' => 'after_open',
                        'separate' => 'bottom',
                    ],
                ),
            ],
        );
    }

    public function isCandidate(Tokens $tokens): bool
    {
        return $this->headerCommentFixer->isCandidate($tokens);
    }

    /**
     * {@inheritdoc}
     *
     * Must run before BlankLinesBeforeNamespaceFixer, SingleBlankLineBeforeNamespaceFixer, SingleLineCommentStyleFixer.
     * Must run after DeclareStrictTypesFixer, NoBlankLinesAfterPhpdocFixer.
     */
    public function getPriority(): int
    {
        return $this->headerCommentFixer->getPriority();
    }

    protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
    {
        // Check if file matches the filtering criteria
        if (!$this->shouldApplyFixToFile($file)) {
            return;
        }

        // Forward configuration to the wrapped HeaderCommentFixer
        $this->forwardConfigurationToHeaderCommentFixer();

        // Delegate to the HeaderCommentFixer
        $this->headerCommentFixer->fix($file, $tokens);
    }

    protected function createConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        return new FixerConfigurationResolver([
            // Forward all HeaderCommentFixer options
            (new FixerOptionBuilder('header', 'Proper header content.'))
                ->setAllowedTypes(['string'])
                ->setNormalizer(static function (Options $options, string $value): string {
                    if ('' === trim($value)) {
                        return '';
                    }

                    if (str_contains($value, '*/')) {
                        throw new InvalidFixerConfigurationException('header_comment_with_filter', 'Cannot use \'*/\' in header.');
                    }

                    return $value;
                })
                ->getOption(),
            (new FixerOptionBuilder('validator', 'RegEx validator for header content.'))
                ->setAllowedTypes(['string', 'null'])
                ->setNormalizer(static function (Options $options, ?string $value): ?string {
                    if (null !== $value) {
                        try {
                            Preg::match($value, '');
                        } catch (PregException $exception) {
                            throw new InvalidFixerConfigurationException('header_comment_with_filter', 'Provided RegEx is not valid.');
                        }
                    }

                    return $value;
                })
                ->setDefault(null)
                ->getOption(),
            (new FixerOptionBuilder('comment_type', 'Comment syntax type.'))
                ->setAllowedValues(['PHPDoc', 'comment'])
                ->setDefault('comment')
                ->getOption(),
            (new FixerOptionBuilder('location', 'The location of the inserted header.'))
                ->setAllowedValues(['after_open', 'after_declare_strict'])
                ->setDefault('after_declare_strict')
                ->getOption(),
            (new FixerOptionBuilder('separate', 'Whether the header should be separated from the file content with a new line.'))
                ->setAllowedValues(['both', 'top', 'bottom', 'none'])
                ->setDefault('both')
                ->getOption(),
            // New filtering options
            (new FixerOptionBuilder('files_pattern', 'Regex pattern to match file paths that should have the header.'))
                ->setAllowedTypes(['string', 'null'])
                ->setNormalizer(static function (Options $options, ?string $value): ?string {
                    if (null !== $value) {
                        try {
                            Preg::match($value, '');
                        } catch (PregException $exception) {
                            throw new InvalidFixerConfigurationException('header_comment_with_filter', 'Provided files_pattern RegEx is not valid.');
                        }
                    }

                    return $value;
                })
                ->setDefault(null)
                ->getOption(),
            (new FixerOptionBuilder('files_regex_exclude', 'Regex pattern to exclude file paths from having the header.'))
                ->setAllowedTypes(['string', 'null'])
                ->setNormalizer(static function (Options $options, ?string $value): ?string {
                    if (null !== $value) {
                        try {
                            Preg::match($value, '');
                        } catch (PregException $exception) {
                            throw new InvalidFixerConfigurationException('header_comment_with_filter', 'Provided files_regex_exclude RegEx is not valid.');
                        }
                    }

                    return $value;
                })
                ->setDefault(null)
                ->getOption(),
        ]);
    }

    /**
     * Check if the fixer should be applied to the given file.
     */
    private function shouldApplyFixToFile(\SplFileInfo $file): bool
    {
        $filePath = $file->getPathname();

        // Check files_pattern: if set, file must match the pattern
        if (null !== $this->configuration['files_pattern']) {
            if (!Preg::match($this->configuration['files_pattern'], $filePath)) {
                return false;
            }
        }

        // Check files_regex_exclude: if matches, skip the file
        if (null !== $this->configuration['files_regex_exclude']) {
            if (Preg::match($this->configuration['files_regex_exclude'], $filePath)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Forward configuration to the wrapped HeaderCommentFixer.
     */
    private function forwardConfigurationToHeaderCommentFixer(): void
    {
        $forwardedConfig = [
            'header' => $this->configuration['header'],
            'validator' => $this->configuration['validator'],
            'comment_type' => $this->configuration['comment_type'],
            'location' => $this->configuration['location'],
            'separate' => $this->configuration['separate'],
        ];

        // Set the configuration on the wrapped fixer
        $this->headerCommentFixer->configure($forwardedConfig);
        // Also forward whitespace configuration
        $this->headerCommentFixer->setWhitespacesConfig($this->whitespacesConfig);
    }
}
